#!/usr/bin/env bash

configure_domain() {
    local domain="$1"

    # Replace these with your actual IP addresses
    web_01_ip="52.206.79.51"
    web_02_ip="52.87.231.218"
    lb_01_ip="54.174.244.191"

    # Add subdomain www pointing to lb-01 IP
    echo "www.$domain IN A $lb_01_ip" >> /etc/bind/db.$domain

    # Add subdomain lb-01 pointing to lb-01 IP
    echo "lb-01.$domain IN A $lb_01_ip" >> /etc/bind/db.$domain

    # Add subdomain web-01 pointing to web-01 IP
    echo "web-01.$domain IN A $web_01_ip" >> /etc/bind/db.$domain

    # Add subdomain web-02 pointing to web-02 IP
    echo "web-02.$domain IN A $web_02_ip" >> /etc/bind/db.$domain

    # Reload DNS configuration
    service bind9 reload
}

display_info() {
    local subdomain="$1"
    local domain="$2"

    # Use dig to get DNS information
    local result=$(dig +short "$subdomain.$domain")

    if [ -n "$result" ]; then
        # Parse the result using awk
        awk -v sub="$subdomain" 'BEGIN { FS = " " } ; { print "The subdomain " sub " is a " $4 " record and points to " $5 }' <<< "$result"
    fi
}

if [ "$#" == 1 ]; then
    domain="$1"
    subdomains=("www" "lb-01" "web-01" "web-02")

    for sub in "${subdomains[@]}"; do
        display_info "$sub" "$domain"
    done
elif [ "$#" == 2 ]; then
    domain="$1"
    subdomain="$2"
    display_info "$subdomain" "$domain"
fi

