#!/usr/bin/env bash

# Installs, configures, and starts the load balancer
sudo apt-get update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get -y install haproxy

# Configuration
DOMAIN_NAME='opendatainc.tech'
INIT_FILE='/etc/default/haproxy'
CONFIG_FILE='/etc/haproxy/haproxy.cfg'
BACKEND_SERVERS=('52.206.79.51:80' '52.87.231.218:80')

# Load balancer configuration
HAPROXY_LB_CONFIG=$(cat <<EOF
#--$DOMAIN_NAME-params-begin--
backend $DOMAIN_NAME-backend
        balance roundrobin
$(printf "\tserver %s check\n" "${BACKEND_SERVERS[@]}")
frontend $DOMAIN_NAME-frontend
        bind *:80
        mode http
        default_backend $DOMAIN_NAME-backend
#--$DOMAIN_NAME-params-end--
EOF
)

# Ensure files exist
touch -c "$INIT_FILE" "$CONFIG_FILE"

# Enable HAProxy
if ! grep -qE '^ENABLED=[01]$' "$INIT_FILE"; then
    echo 'ENABLED=1' >> "$INIT_FILE"
fi

# Update HAProxy configuration
CONFIG_WORDS=$(grep -Eco "$DOMAIN_NAME-backend" < "$CONFIG_FILE")
if [ "$CONFIG_WORDS" -gt 0 ]; then
    start_tkn="#--$DOMAIN_NAME-params-begin--"
    end_tkn="#--$DOMAIN_NAME-params-end--"
    a=$(grep -onE "$start_tkn" < "$CONFIG_FILE" | cut -d : -f1)
    b=$(grep -onE "$end_tkn" < "$CONFIG_FILE" | cut -d : -f1)
    a=$((a - 1))
    b=$((b + 1))
    sed -i "$a,$b"d "$CONFIG_FILE"
fi
echo -en "$HAPROXY_LB_CONFIG" >> "$CONFIG_FILE"

# Restart HAProxy
if pgrep -c haproxy > /dev/null; then
    service haproxy restart
else
    service haproxy start
fi

