#!/usr/bin/env bash
# Fixes the issue with the server

# Update the paths and user based on your Nginx installation
nginx_conf="/etc/nginx/nginx.conf"
default_site="/etc/nginx/sites-enabled/default"
nginx_user="nginx"

if [ -e "$nginx_conf" ]; then
    chmod 644 "$nginx_conf"
    sed -Ei 's/\s*#?\s*user .*/user '"$nginx_user"';/' "$nginx_conf"
fi

if [ -e "$default_site" ]; then
    sed -Ei 's/(listen (\[::\]:)?80) /\180 /' "$default_site"
fi

# Kill Apache if it is running (if necessary)
pkill apache2

